version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}

services:

  # https://hub.docker.com/_/zookeeper
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - frontend

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      - frontend

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      - frontend

  zkui:
    image: maauso/zkui
    restart: always
    environment:
      - ZKLIST=zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 9090:9090
    networks:
      - frontend

  kafka1:
    build:
        context: ./kafka
        args:
          - BROBER_ID=1
          - ZOOKEEPER_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 9092:9092
    networks:
      - frontend
  
  kafka2:
    build:
        context: ./kafka
        args:
          - BROBER_ID=2
          - ZOOKEEPER_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 9093:9092
    networks:
      - frontend

  kafka3:
    build:
        context: ./kafka
        args:
          - BROBER_ID=3
          - ZOOKEEPER_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 9094:9092
    networks:
      - frontend

  kafka-manager:
    image: kafkamanager/kafka-manager
    environment:
      - ZK_HOSTS=zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 9000:9000
    networks:
      - frontend
